### ISSUE TITLE
Helm 'unauthorized' error after repeated make uninstalls

### ISSUE THREAD

**Issue by diemonster** [quintilesims/production_eks_cluster#20]
When uninstalling various addons in (possibly) an incorrect order, `helm` loses `kube-system` perissions/access and returns the following unhelpful error message:

```
helm list
Error: Unauthorized
```

Once `helm` gets into this state, deleting and re-installing `helm` doesn't help.

**Comment by tlake** [comment]
The change to running Tiller locally removes the entire helm addon, and thus sidesteps this issue entirely.
